### ISSUE TITLE
can not process

### ISSUE THREAD

**Issue by mamachengcheng** [asuni/wavelet_prosody_toolkit#26]
Hi, I meet a problem. When I run the tool by going to the root directory of the program in the terminal, and starting by:
`python3` wavelet_prosody_toolkit/wavelet_gui.py`
then, I select directory with speech and transciption files in `samples/`, but I get an error:
```
wavelet_prosody_toolkit/wavelet_gui.py:1026: UserWarning: FixedFormatter should only be used together with FixedLocator
  self.ax[2].set_yticklabels(["sum", "dur", "en", "f0"])
Traceback (most recent call last):
  File "wavelet_prosody_toolkit/wavelet_gui.py", line 674, in onWavChanged
    self.analysis()
  File "wavelet_prosody_toolkit/wavelet_gui.py", line 1036, in analysis
    self.ax[3].set_yticklabels(np.around(self.freqs[:-1],2).astype('str'))
  File "/home/mcc/project/wavelet_prosody_toolkit/venv/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/mcc/project/wavelet_prosody_toolkit/venv/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/mcc/project/wavelet_prosody_toolkit/venv/lib/python3.8/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/home/mcc/project/wavelet_prosody_toolkit/venv/lib/python3.8/site-packages/matplotlib/axis.py", line 1714, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (35), usually from a call to set_ticks, does not match the number of ticklabels (34).

```
Can u help me, thanks

**Comment by seblemaguer** [comment]
Hello,

thanks for the report. It seems that matplotlib has been updated and our code is not up to date. I will check for a fix.

**Comment by seblemaguer** [comment]
Could you try to update your copy of the repository to the last version? It should be solved now.

Thanks

**Comment by mamachengcheng** [comment]
Thank you so much! The issue has been solved.
